name: pobcrawl_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  google_fonts: 6.1.0


flutter:
  uses-material-design: true
  assets:
  # Images
    - assets/images/splash-img.png
    - assets/images/topographic.png
    - assets/images/decor-1.png
    - assets/images/decor-2.png
    - assets/images/decor-3.png
    - assets/images/decor-4.png
    - assets/images/decor-5.png
    - assets/images/decor-6.png
    - assets/images/FAB-img.png
    - assets/images/qr-img.png
    - assets/images/divider-img.png

  # Icons
    - assets/icons/hide-pass-ic.png